kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.name }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
